# Jekyll Configuration for Bluesky Curation
title: "Cooperative Bluesky Curation"
description: "Curated content from our cooperative members on Bluesky"
url: "https://circularmachines.github.io"
baseurl: ""

# Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title.html

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title.html

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Theme
remote_theme: jekyll/minima

# Social
github_username: circularmachines
bluesky_handle: coopcuration.bsky.social

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Curation Bot"
